name: Install Rust

on:
  workflow_dispatch:

jobs:
  install-rust:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          tar -czf rustup-home.tar.gz -C $HOME .cargo .rustup
      
      - name: Commit to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add rustup-home.tar.gz
          git commit -m "Add Rust installation package" || echo "No changes to commit"
          git push
