name: Install Rust

on:
  workflow_dispatch:

jobs:
  install-rust:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Rust and package
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          tar -czf rust-full.tar.gz -C $HOME .cargo .rustup
          ls -lh rust-full.tar.gz
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rust-full
          path: rust-full.tar.gz
